<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BDC11-L-JVXCNN2" name="Portal_Tests.TC001_GenerateStatement" tests="4" failures="1" timestamp="23 Oct 2018 08:30:10 GMT" time="145.617" errors="0">
  <testcase name="TestLogin" time="31.201" classname="Portal_Tests.TC001_GenerateStatement"/>
  <testcase name="CheckBillingSection" time="25.917" classname="Portal_Tests.TC001_GenerateStatement">
    <failure type="java.lang.AssertionError" message="expected [Statements] but found [Billing]">
      <![CDATA[java.lang.AssertionError: expected [Statements] but found [Billing]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Portal_Pages.BillingPage.ToggleScreen(BillingPage.java:84)
at Portal_Tests.TC001_GenerateStatement.CheckBillingSection(TC001_GenerateStatement.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckBillingSection -->
  <testcase name="GenerateStatement" time="62.870" classname="Portal_Tests.TC001_GenerateStatement"/>
  <testcase name="ClosingBrowser" time="25.629" classname="Portal_Tests.TC001_GenerateStatement"/>
</testsuite> <!-- Portal_Tests.TC001_GenerateStatement -->
